## Advent of Code
[Day 3, 2023, part 1](https://adventofcode.com/2023/day/3)

In [1]:
test_input = '''
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

In [2]:
import numpy as np

In [3]:
# add a delimiter for the one-char columns:
def get_numpy_array_from_text_input(text_input: str) -> np.array:
    output_matrix = []
    row_holder = []
    for line in text_input.splitlines():
        for char in line:
            row_holder.append(char)
        output_matrix.append(row_holder)
        row_holder = []

    return np.array(output_matrix[1:])

char_matrix = get_numpy_array_from_text_input(test_input)
char_matrix


array([['4', '6', '7', '.', '.', '1', '1', '4', '.', '.'],
       ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '3', '5', '.', '.', '6', '3', '3', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['6', '1', '7', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '+', '.', '5', '8', '.'],
       ['.', '.', '5', '9', '2', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '7', '5', '5', '.'],
       ['.', '.', '.', '$', '.', '*', '.', '.', '.', '.'],
       ['.', '6', '6', '4', '.', '5', '9', '8', '.', '.']], dtype='<U1')

In [4]:
x, y = char_matrix.shape
print("shape of data: ", x, y)

shape of data:  10 10


In [5]:
import re

digit_re = re.compile('[0-9]')
number_re_match = np.vectorize(lambda x:bool(digit_re.match(x)))
#get the digit mask
num_bool_mask = number_re_match(char_matrix)
num_bool_mask

array([[ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False,  True,  True,  True, False,
        False]])

In [6]:
char_matrix

array([['4', '6', '7', '.', '.', '1', '1', '4', '.', '.'],
       ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '3', '5', '.', '.', '6', '3', '3', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['6', '1', '7', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '+', '.', '5', '8', '.'],
       ['.', '.', '5', '9', '2', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '7', '5', '5', '.'],
       ['.', '.', '.', '$', '.', '*', '.', '.', '.', '.'],
       ['.', '6', '6', '4', '.', '5', '9', '8', '.', '.']], dtype='<U1')

In [7]:
special_character_re = re.compile('(?=[^0-9])(?=[^.])') #not a digit and not a period
special_character_re_match = np.vectorize(lambda x:bool(special_character_re.match(x)))
#get the digit mask
special_char_bool_mask = special_character_re_match(char_matrix)
special_char_bool_mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [8]:
#create an empty array
bloom_mask = [[False]*x]*y
bloom_mask = np.array(bloom_mask)
bloom_mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [9]:
# manually do it again - create a bloom ... if true in l/r/u/d/diag then true ->


def create_bloom_matrix_from_edges(bool_matrix):
    x, y = bool_matrix.shape
    bloom_mask = [[False]*x]*y
    bloom_mask = np.array(bloom_mask)
    
    for i in range(x):
        for j in range(y):
            if bool_matrix[i,j]:
                try:
                    bloom_mask[i-1,j] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j] = True
                except:
                    print('*')
                try:
                    bloom_mask[i,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i,j+1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i-1,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j+1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i-1,j+1] = True
                except:
                    print('*')

    return(bloom_mask)

special_character_bloom_boolean_filter = create_bloom_matrix_from_edges(special_char_bool_mask)

In [10]:
num_bool_mask

array([[ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False,  True,  True,  True, False,
        False]])

In [11]:
from typing import Tuple, List

# def get_number_tuples_from_bloom(special_character_bloom_boolean_filter: np.array
#                                  , char_matrix: np.array
#                                  , num_bool_mask:np.array) -> List[Tuple[int,bool]]:
list_o_numbers = []
str_num = ''
truth_accumulator = False
x, y = special_character_bloom_boolean_filter.shape
for i in range(x):
    for j in range(y):
        if j < y-1:
            if num_bool_mask[i, j] and num_bool_mask[i, j+1]:
                truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                str_num+=char_matrix[i,j]
            if num_bool_mask[i, j] and not num_bool_mask[i, j+1]:
                truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                str_num+=char_matrix[i,j]
                list_o_numbers.append((int(str_num), truth_accumulator))
                str_num = ''
                truth_accumulator = False
                
        else:
            if str_num != '':
                truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                str_num+=char_matrix[i,j]
                list_o_numbers.append((int(str_num), truth_accumulator))
                str_num = ''
                truth_accumulator = False
                
#     return list_o_numbers
# list_o_numbers = get_number_tuples_from_bloom(special_character_bloom_boolean_filter
#                                               , char_matrix
#                                               , num_bool_mask)

In [12]:
list_o_numbers[-50:]

[(467, True),
 (114, False),
 (35, True),
 (633, True),
 (617, True),
 (58, False),
 (592, True),
 (755, True),
 (664, True),
 (598, True)]

#### quick sum where there's an overlap with "bloomed" truth values where there's a special character in the matrix

In [13]:
sum([num for num, boolean in list_o_numbers if boolean])

4361

### Now for the soluition?