## Advent of Code
[Day 3, 2023, part 1](https://adventofcode.com/2023/day/3)

In [1]:
test_input = '''
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

In [2]:
import numpy as np
import re

In [3]:
# add a delimiter for the one-char columns:
def get_numpy_array_from_text_input(text_input: str) -> np.array:
    output_matrix = []
    row_holder = []
    for line in text_input.splitlines():
        for char in line:
            row_holder.append(char)
        output_matrix.append(row_holder)
        row_holder = []

    return np.array(output_matrix[1:])

char_matrix = get_numpy_array_from_text_input(test_input)
char_matrix


array([['4', '6', '7', '.', '.', '1', '1', '4', '.', '.'],
       ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '3', '5', '.', '.', '6', '3', '3', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['6', '1', '7', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '+', '.', '5', '8', '.'],
       ['.', '.', '5', '9', '2', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '7', '5', '5', '.'],
       ['.', '.', '.', '$', '.', '*', '.', '.', '.', '.'],
       ['.', '6', '6', '4', '.', '5', '9', '8', '.', '.']], dtype='<U1')

In [4]:
x, y = char_matrix.shape
print("shape of data: ", x, y)

shape of data:  10 10


In [5]:
char_matrix

array([['4', '6', '7', '.', '.', '1', '1', '4', '.', '.'],
       ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '3', '5', '.', '.', '6', '3', '3', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['6', '1', '7', '*', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '+', '.', '5', '8', '.'],
       ['.', '.', '5', '9', '2', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '7', '5', '5', '.'],
       ['.', '.', '.', '$', '.', '*', '.', '.', '.', '.'],
       ['.', '6', '6', '4', '.', '5', '9', '8', '.', '.']], dtype='<U1')

In [6]:
def get_char_re_mask(character_matrix: np.array, reg_expr: str) -> np.array:
    special_character_re = re.compile(reg_expr) #not a digit and not a period
    special_character_re_match = np.vectorize(lambda x:bool(special_character_re.match(x)))
    #get the digit mask
    special_char_bool_mask = special_character_re_match(character_matrix)
    return special_char_bool_mask

In [7]:
special_char_bool_mask = get_char_re_mask(char_matrix, '(?=[^0-9])(?=[^.])')
special_char_bool_mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

### Get masks by different `re` matches

In [8]:
num_bool_mask = get_char_re_mask(char_matrix, '\d')
num_bool_mask

array([[ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False,  True,  True,  True, False,
        False]])

### **NEW PT II** Gear

In [9]:
gear_bool_mask = get_char_re_mask(char_matrix, '\*')
gear_bool_mask 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [10]:
#create an empty "truth" array
bloom_mask = [[False]*x]*y
bloom_mask = np.array(bloom_mask)
bloom_mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [12]:
# create a bloom ... if true in l/r/u/d/diag then true ->
from typing import Tuple, List

def create_bloom_matrix_from_edges(bool_matrix: np.array) -> (np.array
                                                              , List[Tuple[int, int]]):
    x, y = bool_matrix.shape
    bloom_mask = [[False]*x]*y
    bloom_mask = np.array(bloom_mask)
    coords = []
    
    for i in range(x):
        for j in range(y):
            if bool_matrix[i,j]:
                coords.append((i, j))
                try:
                    bloom_mask[i-1,j] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j] = True
                except:
                    print('*')
                try:
                    bloom_mask[i,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i,j+1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i-1,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j+1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i+1,j-1] = True
                except:
                    print('*')
                try:
                    bloom_mask[i-1,j+1] = True
                except:
                    print('*')

    return(bloom_mask, coords)

special_character_bloom_boolean_filter, coords = create_bloom_matrix_from_edges(special_char_bool_mask)

In [14]:
#New 
gear_bloom_boolean_filter, gear_coords = create_bloom_matrix_from_edges(gear_bool_mask)

In [15]:
from typing import Tuple, List

def get_number_tuples_from_bloom(special_character_bloom_boolean_filter: np.array
                                 , char_matrix: np.array
                                 , num_bool_mask:np.array
                                 , gear_character_bloom_boolean_filter: np.array):
# -> List[Tuple[int,bool, Tuple[Tuple[int,int], int]]]:
    list_o_numbers = []
    str_num = ''
    truth_accumulator = False
    truth_accumulator_gear = False
    start_pos = 0

    x, y = special_character_bloom_boolean_filter.shape
    for i in range(x):
        for j in range(y):
            if j < y-1:
                if num_bool_mask[i, j] and num_bool_mask[i, j+1]:
                    if str_num == '':
                        start_pos=j
                    truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                    truth_accumulator_gear = truth_accumulator_gear or gear_character_bloom_boolean_filter[i,j]
                    str_num+=char_matrix[i,j]
                if num_bool_mask[i, j] and not num_bool_mask[i, j+1]:
                    if str_num == '':
                        start_pos=j
                    truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                    truth_accumulator_gear = truth_accumulator_gear or gear_character_bloom_boolean_filter[i,j]
                    str_num+=char_matrix[i,j]
                    list_o_numbers.append((int(str_num), truth_accumulator, ((start_pos), j), i, truth_accumulator_gear))
                    str_num = ''
                    truth_accumulator = False
                    truth_accumulator_gear = False
                    
            else:
                if str_num != '':
                    truth_accumulator = truth_accumulator or special_character_bloom_boolean_filter[i,j]
                    truth_accumulator_gear = truth_accumulator_gear or gear_character_bloom_boolean_filter[i,j]
                    truth_accumulator_gear = truth_accumulator_gear or gear_character_bloom_boolean_filter[i,j]
                    str_num+=char_matrix[i,j]
                    list_o_numbers.append((int(str_num), truth_accumulator, ((start_pos), j), i, truth_accumulator_gear))
                    str_num = ''
                    truth_accumulator = False
                    truth_accumulator_gear = False
                    
    return list_o_numbers

list_o_numbers = get_number_tuples_from_bloom(special_character_bloom_boolean_filter
                                              , char_matrix
                                              , num_bool_mask
                                              , gear_bloom_boolean_filter)

In [16]:
list_o_numbers

[(467, True, (0, 2), 0, True),
 (114, False, (5, 7), 0, False),
 (35, True, (2, 3), 2, True),
 (633, True, (6, 8), 2, False),
 (617, True, (0, 2), 4, True),
 (58, False, (7, 8), 5, False),
 (592, True, (2, 4), 6, False),
 (755, True, (6, 8), 7, True),
 (664, True, (1, 3), 9, False),
 (598, True, (5, 7), 9, True)]

In [18]:
gear_coords
gear_dict = {}

for value, filter, y_range, x_lim, gear_filter in list_o_numbers:
    if gear_filter:
        y1, y2 = y_range
        closest_gear = [(x, y) for x, y in gear_coords if y>=y1-1 and y<=y2+1 and x>=x_lim-1 and x<=x_lim+1]
        closest_gear_string = str(f"{closest_gear[0][0]}_{closest_gear[0][1]}")
        if closest_gear_string not in gear_dict:
            gear_dict.update({closest_gear_string: [value]})
        else:
            gear_dict[closest_gear_string].append(value)

In [19]:
gear_dict

{'1_3': [467, 35], '4_3': [617], '8_5': [755, 598]}

In [20]:
# multiply then sum the gear_coords
from typing import Dict 

def get_gear_total_from_gear_dict(gear_dict: Dict) -> int:
    gear_total = 0
    for k in gear_dict.keys():
        elem = gear_dict[k]
        if len(elem) > 1:
            prod = np.prod(tuple(elem))
            gear_total+=prod
    return(gear_total)


gear_total = get_gear_total_from_gear_dict(gear_dict)
gear_total

467835

#### quick sum where there's an overlap with "bloomed" truth values where there's a special character in the matrix

In [21]:
non_gear_total = sum([value for value, filter, _, _, gear_filter in list_o_numbers if filter and not gear_filter])

In [22]:
gear_total + non_gear_total

469724

### Now for the soluition?